#!/usr/bin/env node
const fs = require('node:fs');
const path = require('node:path');

const serverBase = process.env.SERVER_BASE || process.env.SHOWDO_SERVER_BASE || '';
const outPath = path.join(process.cwd(), 'config.js');

const content = `// Auto-generated by scripts/generate-config.js\n` +
  `window.SHOWDO_CONFIG = window.SHOWDO_CONFIG || {};\n` +
  `window.SHOWDO_CONFIG.serverBase = ${JSON.stringify(serverBase)};\n`;

try {
  fs.writeFileSync(outPath, content, 'utf8');
  console.log(`Wrote ${outPath} with serverBase=${serverBase || '<empty>'}`);
} catch (err) {
  console.error('Failed to write config.js:', err);
  process.exit(1);
}
